wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.17
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.8
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.6.8
      5: 0.10.17
      8:
      - 1
